export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function RootLayout ({children}) {
    
console.log("ABOUT LAYOUT");
    return (
        <html lang="en">
            <body>
                <h3>Page Only Layout</h3>    
                {children}
            </body>
        </html>
    )
}
